version: '3.9'

services:
  database:
    #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: database_PagSimples_Cadastro
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=pagsimples
      - POSTGRES_DB=cadastro
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: cadastro
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

    links:
      - database
    depends_on:
      - database
volumes:
  pgdata:
    driver: local
